version: 3

includes:
  catalog:
    taskfile: ./catalog-service/Taskfile.yaml
  eureka:
    taskfile: ./eureka-server/Taskfile.yaml
  gateway:
    taskfile: ./api-gateway/Taskfile.yaml

tasks:
  clean:
    desc: Clean all projects
    cmd: ./gradlew clean --parallel
    silent: true
  run:
    desc: Run all projects
    cmd: ./gradlew bootRun --parallel
    silent: true
  test:
    desc: Test all projects
    cmds:
      - task: clean
      - ./gradlew test --parallel
    silent: true

  gradle:stop:
    desc: Stop all gradle daemons
    cmd: ./gradlew --stop
    silent: true