version: "3.8"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=catalog
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - "27017:27017"
